# Generated by Django 4.0.7 on 2023-08-19 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='comments',
            field=models.ManyToManyField(related_name='forum_comments', through='ads.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
