# Generated by Django 4.0.7 on 2023-08-19 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ad',
            new_name='forum',
        ),
    ]
