# Generated by Django 4.0.7 on 2023-09-15 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ads', '0007_fav_ad_favorites_alter_ad_owner_fav_thing_fav_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fav',
            old_name='thing',
            new_name='ad',
        ),
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_ads', through='ads.Fav', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together={('ad', 'user')},
        ),
    ]
