# Generated by Django 4.2.3 on 2023-10-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0009_ad_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="ptext",
            field=models.TextField(null=True),
        ),
    ]
