# Generated by Django 4.0.7 on 2023-07-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnkana', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanacheck',
            name='img',
        ),
        migrations.AddField(
            model_name='kanacheck',
            name='hir',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
